### ISSUE TITLE
[reopen] Can not handle varbinary (ipv4 bin data)

### ISSUE THREAD

**Issue by zloidemon** [tarantool/libslave#7]
I tested with latest patch but doesn't work

```
[2017-05-05 12:29:20] I Connected to Tarantool at 127.0.0.1:3301
[2017-05-05 12:29:21] I Reading binlogs (mysql-bin.000036, 152495292)...
[2017-05-05 12:29:22] E Error in reading binlogs: Slave::create_table(): cannot find collate '' from field originating_ip type varbinary(4) in collate info map
[2017-05-05 12:29:22] E Terminating
```

SQL schema:
```
 CREATE TABLE CDR_Accounts (
  id int(10) unsigned NOT NULL AUTO_INCREMENT,
  i_env tinyint(1) unsigned NOT NULL DEFAULT '1',
  h323_conf_id varchar(36) DEFAULT NULL,
  CLI varchar(128) CHARACTER SET utf8 NOT NULL DEFAULT '',
  CLD varchar(128) CHARACTER SET utf8 NOT NULL DEFAULT '',
  setup_time mediumint(8) unsigned NOT NULL DEFAULT '0',
  connect_time datetime NOT NULL,
  disconnect_time datetime NOT NULL,
  disconnect_cause tinyint(2) unsigned NOT NULL DEFAULT '0',
  voice_quality tinyint(2) unsigned DEFAULT NULL,
  account_id varchar(128) DEFAULT NULL,
  i_dest int(10) unsigned NOT NULL DEFAULT '0',
  charged_time mediumint(8) unsigned NOT NULL DEFAULT '0',
  charged_amount decimal(15,5) DEFAULT NULL,
  history varchar(255) CHARACTER SET utf8 DEFAULT NULL,
  i_vendor int(10) unsigned DEFAULT NULL,
  cost decimal(15,5) DEFAULT NULL,
  i_customer int(10) unsigned NOT NULL DEFAULT '0',
  call_id varchar(100) DEFAULT NULL,
  i_account int(10) unsigned DEFAULT NULL,
  i_tariff int(10) unsigned DEFAULT NULL,
  i_rate int(10) unsigned DEFAULT NULL,
  i_service int(10) unsigned NOT NULL DEFAULT '3',
  bill_time datetime NOT NULL,
  charged_quantity bigint(20) unsigned NOT NULL DEFAULT '0',
  used_quantity bigint(20) unsigned NOT NULL DEFAULT '0',
  bit_flags int(10) unsigned NOT NULL DEFAULT '0',
  h323_incoming_conf_id varchar(36) DEFAULT NULL,
  rating_pattern varchar(247) DEFAULT NULL,
  originating_ip varbinary(4) DEFAULT NULL,
  split_order tinyint(3) unsigned DEFAULT NULL,
  billing_model tinyint(4) DEFAULT NULL,
  peak_level tinyint(4) DEFAULT NULL,
  subscriber_ip varchar(100) DEFAULT NULL,
  i_dest_group int(10) unsigned DEFAULT NULL,
  i_accessibility int(10) unsigned DEFAULT NULL,
  i_invoice int(10) unsigned DEFAULT NULL,
  PRIMARY KEY (id,bill_time),
  KEY bill_time (bill_time),
  KEY conf_id (h323_conf_id),
  KEY env_acc_srv_time (i_env,i_account,i_service,bill_time),
  KEY env_cust_srv_time (i_env,i_customer,i_service,bill_time),
  KEY env_cust_time (i_env,i_customer,bill_time)
) ENGINE=InnoDB
```

**Comment by deadbabe** [comment]
It's weird since current libslave master [doesn't have this error message anymore](/tarantool/libslave/commit/a01c09d7ac36f80af217e2c94713890a2f636e4c#diff-4078640af4703b8ca19b964bf28c970bL199).

Replicator still has older revision, could it be the case?
Then `cd lib/libslave && git checkout master && git pull origin` should help.

**Comment by zloidemon** [comment]
I used to **a01c09d7ac36f80af217e2c94713890a2f636e4c**

```
[2017-05-10 19:18:32] E Error in reading binlogs: Slave::create_table(): cannot find collate '' from field originating_ip type varbinary(4) in collate info map
```

**Comment by deadbabe** [comment]
Anyway, since this code simply not present in master now, it's clear you're linking with older revision somehow.
- Are you building by invoking [build.sh](/tarantool/mysql-tarantool-replication/blob/master/build.sh) (since `git submodule update --init --recursive` command reset submodule revision)
- Sure that there's no older libslave_a.a in your `$LIB`?

**Comment by zloidemon** [comment]
I fully removed libslave and rebuild, i missed with binary file while running over script. I have that at he moment:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff6d4b700 (LWP 5447)]
[New Thread 0x7ffff654a700 (LWP 5448)]

Thread 2 "replicatord" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff6d4b700 (LWP 5447)]
__memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:245
245	../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S: No such file or directory.
(gdb) thread apply all bt

Thread 3 (Thread 0x7ffff654a700 (LWP 5448)):
#0  pthread_cond_timedwait@@GLIBC_2.3.2 () at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:225
#1  0x00000000004737f7 in ?? ()
#2  0x00007ffff76ecc80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff7bc16ba in start_thread (arg=0x7ffff654a700) at pthread_create.c:333
#4  0x00007ffff6e5282d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 2 (Thread 0x7ffff6d4b700 (LWP 5447)):
#0  __memcpy_avx_unaligned () at ../sysdeps/x86_64/multiarch/memcpy-avx-unaligned.S:245
#1  0x00000000004eea6b in void std::vector<unsigned char, std::allocator<unsigned char> >::_M_assign_aux<unsigned char*>(unsigned char*, unsigned char*, std::forward_iterator_tag) ()
#2  0x00000000004eedae in slave::Row_event_info::Row_event_info(char const*, unsigned int, bool, bool) ()
#3  0x00000000004e6f43 in slave::Slave::process_event(slave::Basic_event_info const&, slave::RelayLogInfo&, unsigned long long) ()
#4  0x00000000004e7e4b in slave::Slave::get_remote_binlog(std::function<bool ()> const&) ()
#5  0x0000000000468230 in replicator::DBReader::ReadBinlog(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, unsigned long, std::function<bool (std::unique_ptr<replicator::SerializableBinlogEvent, std::default_delete<replicator::SerializableBinlogEvent> >&&)> const&) ()
#6  0x000000000046edcf in ?? ()
#7  0x00007ffff76ecc80 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#8  0x00007ffff7bc16ba in start_thread (arg=0x7ffff6d4b700) at pthread_create.c:333
#9  0x00007ffff6e5282d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109

Thread 1 (Thread 0x7ffff7fec740 (LWP 5443)):
#0  0x00007ffff7bc298d in pthread_join (threadid=140737326130944, thread_return=0x0) at pthread_join.c:90
#1  0x00007ffff76ecb97 in std::thread::join() () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#2  0x0000000000461d35 in main ()
(gdb) quit
A debugging session is active.

	Inferior 1 [process 5443] will be killed.

Quit anyway? (y or n) y
```

**Comment by deadbabe** [comment]
Should be ok now?

**Comment by zloidemon** [comment]
I tested on latest version yesterday. It works fine for me. thank you.
